### ISSUE TITLE
Add function to "finalize" routes so routes with different signatures can be combined?

### ISSUE THREAD

**Issue by garyb** [owickstrom/hyper#14]
I tried doing something that seemed reasonable, but I couldn't get it to work out in the end as when it came to combining my routes they disagreed, due to using `readBodyAsString` for one of them, and not for the others.

I worked around it just by using `readBody` in a handler instead, to preserve the `RequestBody` type, but I was thinking maybe there's something that could be done so that when you want to combine endpoints in routing the `res` part could be existentially hidden, making the routes compatible.

This possibly ruins some other parts of the design, so perhaps it is impractical, as I guess a `TryMiddleware` router or something it might not fit together anymore? But just throwing it out there as an idea anyway. I still don't know the ins and outs of the design well enough to do much more than handwave here. :smile:

**Comment by owickstrom** [comment]
Oh, interesting! Not sure I have tried that yet with routers. Do you have some code you could share?

Without being sure I understand your problem fully, it sounds reasonable. Hyper is very strict about stuff matching up everywhere. Did your other handler, the one not doing `readBodyAsString`, require a `body :: RequestBody` explicitly? Or could that just be left out of the `request` record, like `Conn { foo: bar {- nothing about the body field here -} | req } ...`? I guess that would line the types up correctly.

**Comment by garyb** [comment]
Yeah, I thought keeping `body` polymorphic in the other routes should have been enough too, but it's not. Here's an example of the case I'm talking about:

``` purescript
module NonUnifyExample where

import Prelude
import Control.Monad.Aff (Aff)
import Control.Monad.Aff.AVar (AVAR)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (log, CONSOLE)
import Control.Monad.Eff.Exception (EXCEPTION)
import Data.Maybe (Maybe)
import Hyper.Core (Middleware, Port(..), ResponseEnded, Status, StatusLineOpen, closeHeaders, fallbackTo, statusNotFound, statusOK, writeStatus)
import Hyper.Node.Server (HttpResponse, RequestBody, defaultOptions, runServer, readBodyAsString)
import Hyper.Response (respond)
import Hyper.Routing.TypeLevelRouter (type (:/), type (:<|>), type (:>), Capture, router, (:<|>))
import Hyper.Routing.TypeLevelRouter.Method (Get, Put)
import Node.Buffer (BUFFER)
import Node.HTTP (HTTP)
import Type.Proxy (Proxy(..))

type AppEffects = (http ∷ HTTP, console ∷ CONSOLE, err ∷ EXCEPTION, avar ∷ AVAR, buffer ∷ BUFFER)

type AppMiddleware bin bout r = Middleware
    (Aff AppEffects)
    { request ∷ { body ∷ bin, contentLength ∷ Maybe Int | r }
    , response ∷ { writer ∷ HttpResponse StatusLineOpen }
    , components ∷ {}
    }
    { request ∷ { body ∷ bout, contentLength ∷ Maybe Int | r }
    , response ∷ { writer ∷ HttpResponse ResponseEnded }
    , components ∷ {}
    }

type Routes
  = "data" :/ Capture "filename" String :> Get
  :<|> "data" :/ Capture "filename" String :> Put

routes ∷ Proxy Routes
routes = Proxy

main ∷ Eff AppEffects Unit
main = do
  runServer defaultOptions onListening onRequestError {} $
  fallbackTo notFound $
  router (Proxy ∷ Proxy Routes) (getData :<|> putData)
  where
  onListening (Port port) = log ("Listening on http://localhost:" <> show port)
  onRequestError err = log ("Request failed: " <> show err)

notFound ∷ ∀ b r. AppMiddleware b b r
notFound = respondWithStatus statusNotFound "Not Found"

getData ∷ ∀ b r. String → AppMiddleware b b r
getData filename =
  respondWithStatus statusOK "OK"

putData ∷ ∀ r. String → AppMiddleware RequestBody String r
putData filename =
  readBodyAsString
  >=> respondWithStatus statusOK "OK"

respondWithStatus ∷ ∀ b r. Status → String → AppMiddleware b b r
respondWithStatus status res =
  writeStatus status
  >=> closeHeaders
  >=> respond res
```

Which results in:

```
  Could not match type

    String

  with type

    RequestBody
```

(From `main`, not `putData` itself)

Now I'm looking at it again I can see why this happens - it's because of the `AppMiddleware b b` usage throughout, which means the input has to match the output, so it ends up being `RequestBody` for both when put into the router. It was less obvious without the synonyms, which I didn't have when I encountered this at first :wink:.

So the "finalize" thing may be unnecessary after all, but some other fixing will be required, as at the moment you can't implement this kind of thing:

``` purescript
respondWithStatus ∷ ∀ b1 b2 r. Status → String → AppMiddleware b1 b2 r
respondWithStatus status res =
  writeStatus status
  >=> closeHeaders
  >=> respond res
```

Since all the functions like `writeStatus`, `respond` are typed with `req` used in both input and output, essentially forcing us to use the `b` for both `body` types.

Maybe all the request-agnostic functons provided by Hyper should have `reqIn` and `reqOut` like I have `bin` and `bout` in my synonym here to work around this... but I'm not totally sure, it seems like that could potentially be problematic too.

**Comment by owickstrom** [comment]
I'm fiddling around with your code. Not sure where, but something is probably unnecessarily constraining. Thanks for the example! :)

**Comment by owickstrom** [comment]
OK, so yeah, the design might be a bit strict in this case. The Node server wants a middleware that returns a Conn, i.e. the router must return a Conn in all cases. Thus all cases must return a Conn of the same type. The reason the server expects a Conn back is so that you get type errors when not having the correct ResponseState (`ResponseEnded`) after having applied all middleware. The last middleware could be `Conn ... -> m Unit`, but then we would lose response state type safety.

It is a very reasonable example, though - only reading the request body in some cases. This feels like it needs some further digging.

**Comment by owickstrom** [comment]
How about throwing away the body value after having used it? A function from a `Conn ...` to `m Conn ...` where the `body` field is `Unit`. You'd have to apply that function to all cases of your routing after the body parser middleware, so that all paths return the same Conn type. That does sound like a way to "finalize". :)

**Comment by owickstrom** [comment]
Revisiting this, I'm thinking that maybe this kind of parsing should be done using return values in the monad, instead of altering the request body of the connection.

```purescript
do
  body <- readBodyAsString
  respond ...
  where bind = ibind
```
Seems like a good tradeoff when it comes to things that only certain handlers need. Things like authentication on the other hand, which probably covers the entire application, might be something you'd want to alter the Conn with.

**Comment by garyb** [comment]
Yep, sounds good to me :+1:

Pre-indexed-monad it seemed less like you were "supposed" to do things that way, since the Kleisli composition was the suggested format for handlers, but that's less the case now. I guess it also means changing `readBodyAsString` to do the appropriate thing rather than remapping `Conn` too.

**Comment by owickstrom** [comment]
Yes, exactly, the Conn return value made that quite awkward. Yep, I'll change that and document it, then close this.

**Comment by owickstrom** [comment]
Fixed in https://github.com/owickstrom/hyper/commit/ea188ca01a76178eb6f40dd1aeb0ea8618905c4e, closing. Thanks!
