### ISSUE TITLE
Support path parameters in Paths

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/hyper#3]
The current Path type is:

```purescript
type Path = Array String
```

It would be nice to have support for path parameters, like string or integer params, at least.

Just thinking out loud, and not knowing at all if it can work, but it would be even better to encode path parameters in the types so that one can not incorrectly `linkTo` or `postTo` a resource. Say that a UserProfile resource has a path like `/users/:userId`, where `:userId` is an integer, then referencing that would require an integer:

```purescript
\conn -> linkTo conn.components.routes.userProfile (IntParam 15) (Text "My Profile")
```

Again, this is just a vision, not sure if it is feasible.

**Comment by hdgarrood** [comment]
Have you seen Yesod's [type-safe routes](http://www.yesodweb.com/book/routing-and-handlers)? I've only used Yesod in one application (Pursuit) but they worked wonderfully there. I think this should definitely be possible. One thing I would say about the Yesod design is that I think that the `PathPiece` type class is a little bit dodgy and I'd quite like to see how well this works just using records like this:

```purescript
type PathPiece a =
  { fromPathPiece :: String -> Maybe a
  , toPathPiece :: a -> String
  }
```

**Comment by owickstrom** [comment]
Yes, I've looked at Yesod, and also some example for Happstack. It is basically the same design I want in Hyper, except the TH. I want to try generically deriving the router implementation from some user-defined data type. The current implementation of routing in Hyper uses records for representing REST resources, but I am working on an ADT-based design also.

In what way do you think the PathPiece class is dodgy? In the sense that there are no obvious instances for common types?

**Comment by hdgarrood** [comment]
I guess in this case it's mostly just that it often makes you want to define orphan instances; in my view, that's a sign that it probably isn't a great fit for a type class. I've also [argued against FromJSON](https://github.com/hdgarrood/aeson-better-errors/issues/4) before and I think some of the same criticisms apply here. In particular, as you note, there may be more than one way of serialising a PathPiece. This is just my view though, and definitely not a universally accepted one.

Also, if you want to derive routers, a type class is probably the way to go, I think.

**Comment by paluh** [comment]
I think that my small routing library could be somehow relevant to this discussion. It provides bidirectional routing based on old Purescript generics (so recursive types are not covered) and "boomerangs" (I've created small haskell boomerang's library port for this purpose). You can check it here:

https://github.com/paluh/purescript-routing-bob

There are still some "dirty" parts like error handling or implementation of query boomerangs which I want to (re)implement, so both libraries are still not published on Pursuit.

Please let me know what do you think.

**Comment by hdgarrood** [comment]
That looks nice, but I think I'd want to have more control over how my types get converted to or from URLs. I'd prefer Yesod's `PathPiece` type class over that approach, I think.

**Comment by paluh** [comment]
Yeah, fully generic approach can be too restrictive for some use cases for sure. I can extend this API and provide more control over some url (de)construction steps (like serialization of constructor names etc.).
It is also possible to create boomerangs by hand too (it is currently not very elegant or simple, but possible: https://github.com/paluh/purescript-boomerang/blob/master/test/Text/Boomerang/String.purs#L21). You can compose these boomerangs (as their form a category) with other boomerangs (created for example generically) to create whole router.

For sure there is a lot of space for improvement in given approach. It is also possible to change it completely, but I think that underlying "boomerangs" abstraction (https://hackage.haskell.org/package/boomerang) which provides composition (and set of simple combinators) is really nice and worthy of consideration.

**Comment by owickstrom** [comment]
I'm leaning towards the Yesod approach, at least for these first router implementations. I'll probably try the `PathPiece` design soon, especially for the ADT-based router. Not sure how it fits with the existing ResourceRouter.

On a related note: I just pushed an [initial implementation of an ADT-based router](https://github.com/owickstrom/hyper/blob/master/src/Hyper/Routing/DataRouter.purs) with some dummy stuff, and [a test with some usage](https://github.com/owickstrom/hyper/blob/master/test/Hyper/Routing/DataRouterSpec.purs), if you'd like to have a look. Just wanted to try out that approach and see how far it holds, and if routing can be both _path safe_ and _method safe_ using types.

**Comment by owickstrom** [comment]
OK, so I took the weekend and made a new router, basically a clone of haskell-servant's routing design: 

**Runnable example:**

https://github.com/owickstrom/hyper/blob/master/examples/type-level-routing/Main.purs

**More exhaustive tests:**

https://github.com/owickstrom/hyper/blob/master/test/Hyper/Routing/TypeLevelRouterSpec.purs (the link extraction part is so neat, even works for nested routes!)

It supports Capture, CaptureAll, nested routers, and some other goodies. I've also added `ToPathPiece` and `FromPathPiece` classes based off of Servant.

Please, I'd like your feedback! I think this design is very promising, and that we can probably scrap the other router hacks. I'd like to make it even smoother, in the sense that you do not have to handle HTTP stuff in your handlers (just declare in the type the Accept, Content-Type, etc, and the router applies your function with the domain type if all is well). Then we could have an extension point and support regular Hyper middleware, in the same way as [Servant supports Raw WAI applications](https://hackage.haskell.org/package/servant-0.9.1.1/docs/Servant-API-Raw.html#t:Raw).

@hdgarrood @paluh

**Comment by paluh** [comment]
Wow! This looks really cool!

**Comment by owickstrom** [comment]
I hope to soon have something Servant-like with Accept/Content-Type type constraints, as well as JSON and Form body parsers and serializers. Then the raw middleware can be an optional "low-level" way of handling requests. Handler functions can instead have nice types like `createThing :: ThingForm -> Either SomeError Thing` and provide ToJSON, ToHTML, or FromFormData instances for `Thing`. Anyway, this is a bit off-topic for this issue. Just wanted to get your two cents on how to proceed, if the existing router implementations should be abandoned (I think so, but not entirely sure yet).

**Comment by hdgarrood** [comment]
Looks great! I'll definitely have a play with it next time I want a web server in purescript.

**Comment by owickstrom** [comment]
Nice! 😄 

I'll close this ticket, then.
