### ISSUE TITLE
Handle `Set-Cookie` attributes

### ISSUE THREAD

**Issue by paluh** [owickstrom/hyper#41]
Hyper's `setCookie` is missing [`Set-Cookie` attributes setup](https://tools.ietf.org/html/rfc6265).

I've implemented attribute handling on this [branch](https://github.com/paluh/hyper/compare/master...paluh:set-cookie-attributes).

Some notes:

* I've added `Hyper.Cookie.setCookieHeaderValue` function (separate from `setCookie`) because I want to reuse this serializer in `hyperdrive` application context

* I've added this attributes setup to `Hyper.Session.saveSession`: `SameSite=Lax;HttpOnly`, but probably this setup should be even more configurable

* I've added this attribute setup to `Hyper.Session.deleteSession`: `MaxAge=0`

* In [theory](https://tools.ietf.org/html/rfc6265#section-3.1) we should allow setup of multiple `Set-Cookie` headers, but I've read that fortunately it is not widely adopted, so we can stick probably with current behavior

* I'm really open to any suggestion to improve/change coding style of my chages

Should I provide PR with these changes?

**Comment by owickstrom** [comment]
Very nice! Let me look at this after work and get back to you. Thanks! :+1:

**Comment by paluh** [comment]
I've merged this PR already.
