### ISSUE TITLE
Hyper app crashes on thrown exceptions

### ISSUE THREAD

**Issue by bklaric** [owickstrom/hyper#44]
In [Server.purs](https://github.com/owickstrom/hyper/blob/64430238826531d7c26a3e174bd5ce59dc55b545/src/Hyper/Node/Server.purs#L253), Hyper uses a combination of `launchAff` and `catchException` to run the `Aff` computation. However, `catchException` is not guaranteed to catch the exception if the exception is thrown asynchronously, as documented [here](https://pursuit.purescript.org/packages/purescript-aff/3.1.0/docs/Control.Monad.Aff#v:launchAff).

This, coupled with #43 makes it possible to crash a Hyper app by appending an invalid query string, like `?%%%`, to a URL.

A possible fix is to replace `launchAff` with `runAff` and having the successful callback do nothing. This doesn't crash the app, but doesn't return any response either. It would be nice if the user could specify an "uh oh, an unexpected error occurred" response to return in such cases. I'm not sure how that would work though.

**Comment by owickstrom** [comment]
I see! If we change to use `runAff`, then we can use the existing `onRequestError` from the `Options` type to catch all exceptions. The successful callback should do nothing, as the request handler then has sent a response. Or am I mistunderstanding you?

Thanks!

**Comment by bklaric** [comment]
That's correct, yes. I'll whip up a PR so we can see it in action.

**Comment by owickstrom** [comment]
This can be closed now, correct?

**Comment by bklaric** [comment]
Correct.
