### ISSUE TITLE
Add hyper to package-sets

### ISSUE THREAD

**Issue by paluh** [owickstrom/hyper#54]
Today I've added `indexed-monad` to package-sets and verified that after migration to aff-4.0.0 all dependencies are met and we can add hyper to the packages index.
I will happily provide appropriate pull request to package-sets repo.

**Comment by owickstrom** [comment]
Sounds good! We should release a new version of Hyper then. Maybe we want the Node response stream issue resolved first?

**Comment by paluh** [comment]
I want to provide additional pull request with cookie attributes implementation before this release if you don't mind...

**Comment by nsaunders** [comment]
This is done. I've added a badge to the README that shows the latest package set that includes Hyper.
