### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by nsaunders** [owickstrom/hyper#72]
The list of [commits to ```master```](https://github.com/owickstrom/hyper/commits/master) since [```v0.8.0```](https://github.com/owickstrom/hyper/commits/v0.8.0) is quite lengthy, so a new release is probably quite overdue.

I have updated the outdated portions of the docs (see #73).

Aside from that, here are the remaining tasks as I see it:
* ~~Migrate documentation to RTD or similar (see #71).~~ (Not doing this yet; see below.)
* ~~Review commits referenced above~~ (done) and
  - ~~Formulate a new [```CHANGELOG.md```](https://github.com/owickstrom/hyper/blob/master/CHANGELOG.md) entry.~~
  - ~~Revise docs as needed.~~ Nothing required here.

Anything I've missed?

**Comment by owickstrom** [comment]
Sounds good! If you want to push on the RTD task, I could upload to the old S3 location for this release, and not have it depend on the RTD migration?

**Comment by nsaunders** [comment]
That would be great! I will work on a changelog entry then and also see if the documentation is missing anything.

**Comment by owickstrom** [comment]
Neat!

**Comment by nsaunders** [comment]
@owickstrom if you're OK with everything, then, aside from uploading the new docs, perhaps you might as well tag and publish this new version. If you'd rather have me take care of it, please let me know.

**Comment by owickstrom** [comment]
If you could give it a go, I think it would be great! So that you've also tried the process out and I'm not the only one who can release. If anything does need me to do it, then I'll gladly jump in.

**Comment by nsaunders** [comment]
@owickstrom I have [created the 0.9.0 tag](https://github.com/owickstrom/hyper/releases/tag/v0.9.0) and [published to Pursuit](https://pursuit.purescript.org/packages/purescript-hyper/0.9.0), so that just leaves the docs to you, whenever you get a chance to publish them.
